#!/bin/bash

echo "Restarting server ..."
killall ircbrowse -q

while true
do
    if ps -C ircbrowse > /dev/null
    then
       echo Waiting...;
    else
       break;
    fi
done

dist/build/ircbrowse/ircbrowse ircbrowse.conf 1>/dev/null 2>/dev/null & disown
